FROM eclipse-temurin:11 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:11-jre-slim
COPY --from=build /target/CSProConnect-0.0.1-SNAPSHOT.jar CSProConnect.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "CSProConnect.jar"]