FROM 3.9.6-eclipse-temurin-11 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:23-slim-bullseye
COPY --from=build /target/CSProConnect-0.0.1-SNAPSHOT.jar CSProConnect.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","CSProConnect.jar"]